/*============================================================
Project : Coffee Shop Sales Analysis
File    : 05_Store_Analysis.sql
Purpose : Analyze store performance to identify high and low
          performing branches.
Author  : Biki Jana
============================================================*/

USE CoffeeShopSales;

--------------------------------------------------------------
-- Business Request:
-- Calculate revenue generated by each store.
--------------------------------------------------------------

SELECT
    store_location,
    SUM(transaction_qty * unit_price) AS Revenue
FROM coffee_shop_sales
GROUP BY store_location
ORDER BY Revenue DESC;

--------------------------------------------------------------
-- Business Request:
-- Count transactions for each store.
--------------------------------------------------------------

SELECT
    store_location,
    COUNT(*) AS Total_Transactions
FROM coffee_shop_sales
GROUP BY store_location
ORDER BY Total_Transactions DESC;

--------------------------------------------------------------
-- Business Request:
-- Calculate total quantity sold by each store.
--------------------------------------------------------------

SELECT
    store_location,
    SUM(transaction_qty) AS Quantity_Sold
FROM coffee_shop_sales
GROUP BY store_location
ORDER BY Quantity_Sold DESC;

--------------------------------------------------------------
-- Business Request:
-- Calculate Average Order Value for every store.
--------------------------------------------------------------

SELECT
    store_location,
    SUM(transaction_qty * unit_price) / COUNT(*) AS Average_Order_Value
FROM coffee_shop_sales
GROUP BY store_location
ORDER BY Average_Order_Value DESC;

--------------------------------------------------------------
-- Business Request:
-- Count unique products sold by each store.
--------------------------------------------------------------

SELECT
    store_location,
    COUNT(DISTINCT product_detail) AS Unique_Products
FROM coffee_shop_sales
GROUP BY store_location
ORDER BY Unique_Products DESC;

--------------------------------------------------------------
-- Business Request:
-- Compare product category revenue across stores.
--------------------------------------------------------------

SELECT
    store_location,
    product_category,
    SUM(transaction_qty * unit_price) AS Revenue
FROM coffee_shop_sales
GROUP BY
    store_location,
    product_category
ORDER BY
    store_location,
    Revenue DESC;

